a=[1,4,3,5,2]
print("\n")
print("list is ",a)
b=(1,2,3,4,5)
li=list(b)
print("list created from tuple is ",li)
l=len(a)
print("length of list a is ",l)
a.sort()
print("sorted list is ", a)
a.reverse()
print("reverse of string is ",a)
a.append(6)
print("appended list is", a)
a.clear()
print("cleared list is ",a)